davidahouse/stampede-server

events/pullRequest.js
This PR fixes the clone URLs used for a PR from a forked repo. It wasn't using the correct url and was cloning the main repo, not the forked one.
closes #158
=> 🐛 Fixed bug causing forked repo to be cloned incorrectly

events/checkRun.js
This PR fixes a bug that was happening when a single check run was requested.
closes #162
=> 🐛 Fixed bug in single check run request

controllers/repositories/executeTask.js
This PR fixes a bug when manually executing a task for a PR.
closes #198
=> 🐛 Fix for running manual PR task

lib/taskExecute.js
This PR makes a few more fixes related to the manual task execution for a pull request event type.
closes #198
=> 🐛More fixes for manual task pull request executions

controllers/monitor/workers.js
This PR updates the monitor workers screen, sorting the workers by node and worker name.
closes #197
=> ✨ Now sorting the workers

controllers/monitor/activeTasks.js, views/monitor/activeTasks.pug
This PR updates the active tasks screen to add node and sort by node as well.
closes #196
=> ✨ Add node to active tasks list

scm/github.js
This PR fixes a bug in the octokit import that was causing some issues in the GitHub integration
closes #213
=> 🐛 Fixed octokit import

events/push.js, events/release.js, package-lock.json, package.json
This PR fixes some issues where the build key could get spaces or other characters that were not safe for creating folders with.
closes #215
=> 🐛 Sanitized build key to ensure it is safe for folder names

controllers/repositories/repositoryDetails.js, controllers/repositories/selectConfigSource.js, controllers/repositories/toggleConfigSource.js, lib/ui.js, views/repositories/selectConfigSource.pug
This PR fixes a bug in the repository config cache flow when trying to remove the cached config.
closes #173
=> 🐛 Fixed bug in repo config cache flow in chrome

bin/stampede-server.js, lib/build.js, package-lock.json, package.json, scm/github.js, scm/testMode.js
This PR adds a general check to every PR run that has a `Neutral` status, but serves as a place where general errors can be reported, information can be shown and actions can be added for running ad-hoc builds. More goodies coming to this check soon, this is just the foundation. For now this check includes a link to the Stampede UI for checking on the build status.
closes #144
=> ✨ Added general stampede check to PRs

events/pullRequest.js, lib/checkRun.js, scm/github.js, scm/testMode.js
This PR adds a note to the stampede check if no tasks are found. That might indicate the stampede yaml is malformed, or you just didn't put any tasks in there. Either way this is no longer a silent failure as no build will be created.
closes #143
=> ✨ Now showing no tasks to run in the stampede check

scm/github.js
This PR allows you to set the title and description for an action in the .stampede.yaml file. For example:
```
actions:
- id: my-task
title: The Title
description: Some kind of description
```
Otherwise they default to the task id.
closes #226
=> ✨ pull title and description from action if found

scm/github.js
This PR fixes a bug when the system was attempting to create the stampede check when actions were present.
closes #228
=> 🐛 Fixed bug when creating the stampede check

bin/stampede-server.js, controllers/repositories/executeRepositoryBuild.js, controllers/repositories/removeRepositoryBuild.js, controllers/repositories/repositoryBuildDetails.js, controllers/repositories/repositoryDetails.js, controllers/repositories/uploadRepositoryBuild.js, lib/repositoryBuild.js, lib/taskExecute.js, lib/ui.js, package-lock.json, package.json, views/repositories/repositoryBuildDetails.pug, views/repositories/repositoryDetails.pug
This PR introduces a new build type: Repository Build. These builds are not triggered from any GitHub events, but can be triggered manually or on a schedule.This PR creates a UI for managing the builds and executing them. The server also includes the logic for executing them on a daily schedule if the schedule has been set. Note this is just a MVP for this functionality, some UI cleanup would be nice along with more types of schedules (this only supports a daily execution after a specific time).
=> ✨Repository builds

bin/stampede-server.js
This PR just tweaks the logging in the new repository builds schedule.
closes #237
=> ♻️ Tweaks to schedule logging

lib/api.js, lib/ui.js
This PR fixes an issue with the path detection for the dynamic routes.
closes #248
=> 🐛 Fixed pathing for dynamic route detection

events/pullRequest.js, lib/checkRun.js
This PR adds more details to the Pull Request section that is sent to tasks. The bodyLength, milestone and labels are sent so that tasks can be built that use them.
closes #250
=> ✨ Added more PR details that are sent to the task

controllers/admin/uploadDefaults.js
This PR fixes a bug when trying to upload defaults.
=> 🐛 Fixed bug in upload defaults screen

controllers/repositories/executeTask.js, controllers/repositories/executeTaskConfig.js, lib/taskExecute.js
This PR fixes an issue with manual task execution. It wasn't passing all the complete Pull Request details to the actual task execution.
=> 🐛 Fixed issue with passing pr details on manual execute

views/history/taskDetails.pug, views/monitor/buildTaskDetails.pug, views/repositories/taskDetails.pug
This PR fixes a bug in the summary text rendering on the task details screen.
closes #262
=> 🐛 fixed bug in summary rendering

views/history/taskDetails.pug, views/monitor/buildTaskDetails.pug, views/repositories/taskDetails.pug
This PR fixes some markdown issues in task details screens. Basically it wasn't rendering at all… :(
=> 🐛 Fixed markdown render issue

controllers/repositories/toggleConfigSource.js
This PR fixes an issue when removing a cached config.
closes #274
=> 🐛 Fixed bug when removing cached config

controllers/history/buildSummary.js, controllers/history/builds.js, controllers/repositories/repositoryDetails.js, lib/db.js, views/history/builds.pug
This PR adds a filter section on the Build history page. You can filter by timeframe, build key and repository.
closes #191 
closes #190
=> ✨ Build history now filterable

controllers/admin/repositoryAdmin.js, controllers/repositories/repositoryDetails.js
This PR sorts the repository build list on repository details and repository admin pages so they are easier to find when there are many of them.
closes #311
=> ✨ Repository build list is now sorted when displayed

controllers/repositories/repositoryDetails.js, views/repositories/repositoryDetails.pug
This PR adds a link to the build details for any active builds in the repository details screen.
closes #310
=> ✨ Added link to active build details

views/history/buildTaskDetails.pug
This PR fixes the markdown rendering of task details if you get there via build details.
closes #312
=> 🐛 Fixed build task details summary and text

controllers/history/buildDetails.js, controllers/history/buildTaskDetails.js, controllers/history/taskDetails.js, controllers/monitor/buildDetails.js, controllers/monitor/buildTaskDetails.js, controllers/repositories/buildDetails.js, controllers/repositories/taskDetails.js, views/history/buildDetails.pug, views/history/buildTaskDetails.pug, views/history/taskDetails.pug, views/monitor/buildDetails.pug, views/monitor/buildTaskDetails.pug, views/repositories/buildDetails.pug, views/repositories/taskDetails.pug
This PR updates the UI for build & task details to support showing artifacts if they have been returned by a task. Artifacts are simply links that are added to the task result. Currently the only option we will provide is to download the file contained in the link. But in the future we could offer to install an app if this is a mobile app. Or perhaps other special behaviors.
closes #298
=> ✨ UI now support build and task artifacts

lib/ui.js, views/components/sideBar.pug
This PR fixes a spacing issue & sort order in the owners list in the sidebar.
closes #321
=> 🐛 Fixed spacing for owners in repository menu

views/monitor/activeTasks.pug
This PR updates the active task list to show the node at the end of the list of columns.
closes #212
=> ♻️Reordered columns on active task list

controllers/repositories/executeRepositoryBuild.js, controllers/repositories/executeRepositoryBuildWithBranch.js, controllers/repositories/selectRepositoryBuildBranch.js, views/repositories/selectRepositoryBuildBranch.pug
This PR allows repository builds to specify `$select` as the branch which will trigger a UI to enter a branch that the build will execute against. This allows for ad-hoc style builds when we don't know the branch ahead of time.
closes #324
=> ✨ Added option to select branch for repository builds

controllers/admin/repositoryBuildDetails.js, views/admin/repositoryBuildDetails.pug
This PR updates the repository build details screen to show the raw yaml from the build. This should let admins better see the details that are loaded on the server. And opens the way to in-browser editing once we get a YAML editor integrated.
=> ✨ Now showing build yaml in repository build details

controllers/repositories/buildDetails.js, views/history/buildDetails.pug, views/monitor/buildDetails.pug, views/repositories/buildDetails.pug
This PR changes the task list on build details to show the conclusion for completed tasks instead of the status that just says completed. Now you can see if the tasks were a success or failure.
closes #329
=> ♻️ Instead of task status show task conclusion for completed tasks

controllers/admin/repositoryAdmin.js, controllers/admin/uploadRepositoryBuild.js, views/admin/repositoryAdmin.pug
This PR adds error handling when uploading a repository build. If the yaml is invalid, an error will display back on the repository admin screen instead of crashing the server.
closes #328
=> 👷‍♂️ Now providing correct error if repo build contains invalid yaml

controllers/history/builds.js, lib/db.js
This PR adds a couple of additional time filters to history builds screen.
closes #341
=> ✨ Added more items to time filter on history builds

views/history/buildDetails.pug, views/history/buildTaskDetails.pug, views/history/taskDetails.pug, views/monitor/buildDetails.pug, views/monitor/buildTaskDetails.pug, views/repositories/buildDetails.pug, views/repositories/taskDetails.pug
This PR adds a link type to the artifact list which changes the button title.
closes #343
=> ✨ Showing open button for link type artifacts

controllers/history/buildTaskDetails.js, controllers/history/taskDetails.js, controllers/monitor/buildTaskDetails.js, controllers/repositories/taskDetails.js, events/push.js, views/history/buildTaskDetails.pug, views/history/taskDetails.pug, views/monitor/buildTaskDetails.pug, views/repositories/taskDetails.pug
This PR adds additional details to the task details screens, including the scm event related details for pull request, branch or release events.
closes #345
=> ✨ Added scm details to all task details screens

lib/checkRun.js
Fixed a bug where PR actions weren't getting an access token generated.
closes #349
=> 🐛 Now getting access token for pr actions

controllers/admin/repositoryAdmin.js, controllers/admin/uploadOrgConfigDefaults.js, controllers/admin/uploadOrgConfigOverrides.js, controllers/admin/uploadRepoConfigDefaults.js, controllers/admin/uploadRepoConfigOverrides.js
This PR fixes a few bugs related to uploading an invalid yaml file for defaults or overrides.
closes #353
=> 🐛 Fixed some bugs if uploading invalid defaults or overrides

views/components/sideBar.pug, views/history/layout.pug, views/layout.pug
This PR adjust the colors so the sidebar doesn't lose its background color when the screen scrolls.
closes #177
=> 💄 Adjusted colors to prevent sidebar from losing background on scroll

views/components/tableCellButton.pug
This PR fixes some buttons in the UI that caused it to be hard to click as only the text was clickable.
closes #352
=> 🐛 Fixed bug causing some buttons to be hard to click

controllers/history/buildTimeByNode.js, controllers/history/buildTimeByOrg.js
This PR fixes the colors on the pie charts.
closes #357
=> 🐛 fixed random colorness

controllers/history/taskHealth.js, lib/db.js, views/components/sideBar.pug, views/history/taskHealth.pug
This PR adds a Task Health screen under History.
closes #373
=> ✨ Added a task health page to history

api/recentBuilds.js
This PR corrects the recent builds API.
closes #366
=> ♻️ Corrected recent builds api

views/repositories/buildDetails.pug, views/repositories/repositoryDetails.pug, views/repositories/taskDetails.pug
This PR fixes the links in the breadcrumb trail while in the repository flows.
closes #371
=> 🐛 Fixed links in the repository screens

controllers/history/hourlySummary.js, lib/db.js, views/components/sideBar.pug, views/history/hourlySummary.pug
This PR adds an hourly summary to view the last 24 hours of activity. Similar to daily summary.
closes #387
=> ✨ Added an hourly summary

api/history/hourlySummary.js
This PR adds an api endpoint for the hourly summary data.
closes #388
=> ✨API for hourly summary

api/monitor/activeBuilds.js
This PR fixes the active builds API to match how the controller for monitor/activeBuilds works.
closes #365
=> ♻️Fixed the active builds api to match controller behavior

api/repository/repositoryBuilds.js
This PR adds an API for getting the repository builds list for a repository. This will include scheduled builds, manual builds and any active builds for that repository.
closes #386
=> ✨ New API for getting repository builds list

.gitignore, .ubolt.yaml, controllers/admin/removeRepository.js, controllers/admin/removeRepositoryConfirm.js, lib/db.js, views/admin/removeRepositoryConfirm.pug, views/admin/repositoryAdmin.pug
This PR adds a delete repository option to the repository admin screen.
closes #402
=> ✨ Added an ability to delete a repository

bin/stampede-server.js, events/push.js, lib/db.js, lib/task.js
This PR adds a config option to log any slow database queries.
closes #413
=> 🚨 Added logging option for slow db queries

controllers/repositories/buildDetails.js, controllers/repositories/executeRepositoryBuildWithBranch.js, controllers/repositories/repositoryDetails.js, views/repositories/repositoryDetails.pug
This PR adds back an Active Builds section on the repository details page. Hopefully I don't just remove it again, but for now going to try it again.
closes #417
=> ♻️ Moved active builds back to the top

bin/stampede-server.js, controllers/repositories/repositoryDetails.js, controllers/repositories/repositorySourceDetails.js, events/pullRequest.js, events/push.js, events/release.js, lib/build.js, lib/checkRun.js, lib/db.js, lib/repositoryBuild.js, lib/taskExecute.js, views/repositories/repositoryDetails.pug, views/repositories/repositorySourceDetails.pug
This PR changes the repository details screen, adding a branch builds section. This will show any branches that have been built for the repository. Note that this is capturing builds that are started via a branch push event. So PRs, releases and repository manual/scheduled builds will not show up here. Clicking on the branch will take you to the details for just that branches builds.
closes #419
=> ✨Add branch builds to repository details

controllers/repositories/repositoryDetails.js, lib/db.js, views/repositories/repositoryDetails.pug
This PR adds a release build list to the repository details screen. Now you can quickly see and drill into the latest releases for a repository.
closes #420
=> ✨ Added a release build list to repository details

controllers/repositories/repositoryDetails.js, views/repositories/repositoryDetails.pug
This PR adds a pull request section to the repository details screen. This will show the most recently updated pull requests and allow you to drill down into the details.
closes #421
=> ✨ Added pull requests section to repository details

bin/stampede-server.js
This PR adds a config option to disable the build scheduler.
closes #435
=> ✨ Added config option to disable the scheduler

controllers/history/deleteBuild.js, lib/db.js, views/history/buildDetails.pug
This PR adds a delete button for builds if you are logged in as an admin.
closes #441
=> ✨ Now admin can delete builds

views/history/buildDetails.pug, views/repositories/buildDetails.pug
This PR adds an `Archived` note on the build details screens.
closes #453
=> ✨Added an archived note on the build details screens

controllers/history/tasks.js, views/history/tasks.pug
This PR adds duration to the task history list.
closes #485
=> ✨ Added duration to task history list

api/repository/repositoryBuilds.js
This PR modifies the repositoryBuilds api to return just the list of builds along with the last executed time. This matches the UI when going into repository details.
closes #493
=> ♻️ Modified repository builds api

controllers/history/buildTaskDetails.js, controllers/history/taskDetails.js, controllers/repositories/taskDetails.js, views/history/buildTaskDetails.pug, views/history/taskDetails.pug, views/repositories/taskDetails.pug
This PR updates a few of the task details screens to include start and finished time along with duration. Now it will be easier to see how long tasks are taking to execute.
closes #486
=> ♻️ Added consistent start and finish times to task details

views/admin/defaults.pug, views/admin/overrides.pug, views/admin/viewOrgConfigDefaults.pug, views/admin/viewOrgConfigOverrides.pug, views/admin/viewRepoConfigDefaults.pug, views/admin/viewRepoConfigOverrides.pug
Since these are just display values, I figured they'd be simple to correct.
=> Correct typos in some display values

controllers/repositories/repositoryDetails.js, views/components/tableHeader.pug, views/repositories/repositoryDetails.pug
This PR updates the Repository Details page to include a last executed date next to each of the build sections. It also adds a more friendly message if no builds are found.
closes #448
=> ✨ Added last executed date to repo details

controllers/monitor/cancelBuild.js
This PR cleans up the cancel build flow so that the tasks will be marked as cancelled correctly in GitHub.
closes #96
=> 🐛 Cleaned up canceled build process

api/history/archivedBuildWithTaskDetails.js, api/history/hourlySummary.js, api/history/tasks.js, api/monitor/activeBuilds.js, api/monitor/activeTasks.js, api/repository/buildKeys.js, api/repository/repositoryBuilds.js, lib/cache/cache.js, lib/cache/repositoryBuilds.js, lib/cache/systemQueues.js, lib/db.js, lib/web.js
This PR fixes some error handling in the API calls.
closes #409
=> 🐛 Fixed some unhandled errors in the api calls

api/history/archivedBuildWithTaskDetails.js, api/history/removeTaskDetails.js, lib/db.js
This PR includes task artifacts along with taskDetails in the APIs that deal with archived builds. Now the artifacts will appear in the task details json when requesting an archived task, and when removing task details the artifacts are also removed.
closes #533
=> ✨ Now deleting task artifacts along with task details

bin/stampede-server.js, lib/build.js, lib/cache/cache.js, lib/notification.js, lib/notificationChannels/slack.js, lib/taskUpdate.js
This PR implements basic notification support, allowing projects to add a `notifications:` section to a build. Also included here is a basic slack Webhook integration.
closes #537
=> ✨Basic notification support

bin/stampede-server.js, lib/build.js, lib/incomingHandler.js, lib/task.js, lib/taskUpdate.js, scm/events/checkRun.js, scm/events/checkSuite.js, scm/events/pullRequest.js, scm/events/push.js, scm/events/release.js, services/incomingQueue.js, services/notification.js, services/responseQueue.js, services/slackNotificationQueue.js, services/web.js, services/web/api.js, services/web/incoming.js, services/web/ui.js
This PR includes a refactor of the lib folder and the creation of a services folder. The stampede server main js file is also refactored to use these services instead of embedding that code directly into the main js. More improvements are still possible to do, as some of the interactions between files is not handled well. But for now this is a good improvement and will make adding new services much easier.
closes #541
=> ♻️Refactor services and lib folder

.ubolt.yaml, bin/stampede-server.js, lib/db.js, lib/notificationChannels/prComment.js, scm/github.js, scm/testMode.js, services/prCommentNotificationQueue.js, services/web.js, services/web/api.js
This PR implements a PR commenting notification channel that users can configure for a PR build. This will comment on the PR once the build is complete and tell you if the checks passed or failed. This is to help give visibility to developers if they aren't checking the checks results. If they have notifications turned on correctly in GitHub they should get an email with the comment.
Note: this is the bare bones implementation and there is room for improvement (more/less snark and gifs/no-gifs).
closes #507
=> ✨PR Comment notification channel

.stampede.yaml
This PR updates the stampede config for this repo to enable PR comments and slack notifications.
=> 🐎 Adding notifications

.stampede.yaml
This PR adds a lines-of-code task to the stampede config.
=> 🐎 Added lines of code task

lib/notificationChannels/prComment.js, scm/testMode.js
This PR updates the PR comment and adds a list of artifacts.
closes #549
=> ✨ Added artifact list to the pr comment

controllers/history/buildDetails.js, controllers/history/buildTaskDetails.js, controllers/history/taskDetails.js, controllers/repositories/buildDetails.js, controllers/repositories/taskDetails.js, lib/notificationChannels/prComment.js, lib/taskUpdate.js
This PR fixes a bug found in artifact URLs that were missing encoding.
closes #559
=> 🐛 fixed bug missing encoded artifact urls

controllers/artifacts/viewUnknown.js, controllers/history/buildDetails.js, controllers/history/buildTaskDetails.js, controllers/history/taskDetails.js, controllers/repositories/buildDetails.js, controllers/repositories/taskDetails.js, lib/notificationChannels/prComment.js, lib/taskUpdate.js, views/artifacts/viewUnknown.pug, views/history/buildDetails.pug, views/history/buildTaskDetails.pug, views/history/taskDetails.pug, views/repositories/buildDetails.pug, views/repositories/taskDetails.pug
This PR adds viewing of unknown artifact types.
closes #570
=> ✨ Enabled viewing of unknown artifact types

controllers/artifacts/viewXcodebuild.js, controllers/history/buildDetails.js, controllers/history/buildTaskDetails.js, controllers/history/taskDetails.js, controllers/repositories/buildDetails.js, controllers/repositories/taskDetails.js, lib/notificationChannels/prComment.js, lib/taskUpdate.js, views/artifacts/viewXcodebuild.pug
This PR adds a viewer for the `xcodebuild` artifact type. This artifact contains test execution details and code coverage details for a test execution using the `xcodebuild` command line tool.
closes #571
=> ✨ Added xcodebuild result artifact viewer

controllers/artifacts/viewImageGallery.js, controllers/history/buildDetails.js, controllers/history/buildTaskDetails.js, controllers/history/taskDetails.js, controllers/repositories/buildDetails.js, controllers/repositories/taskDetails.js, lib/notificationChannels/prComment.js, lib/taskUpdate.js, views/artifacts/viewImageGallery.pug
This PR adds an image gallery artifact type viewer.
closes #576
=> ✨Added image gallery artifact type

lib/notificationChannels/prComment.js
This PR adds more details in the PR Comment for a successful build.
closes #580
=> ✨ Added more details in the success pr comment

lib/notificationChannels/slack.js
This PR improves the text output in the slack notifications.
closes #581
=> ♻️ Improvements to slack notifications

lib/notificationChannels/prComment.js
This PR fixes some spacing issues in the PR comment in the artifacts section.
=> 🐛 fixed spacing in pr comment artifacts

api/history/latestArtifact.js, lib/db.js
This PR adds an API to retrieve the latest artifact details for a particular artifact.
closes #587
=> ✨ Added an API for getting the latest artifact details

api/repository/taskDetails.js
This PR adds a taskDetails API endpoint for fetching more details for a specific task, including artifacts.
closes #598
=> ✨ Added a taskDetails api endpoint

api/repository/taskDetails.js, controllers/artifacts/viewImageGalleryDiff.js, controllers/history/buildDetails.js, controllers/history/buildTaskDetails.js, controllers/history/taskDetails.js, controllers/repositories/buildDetails.js, controllers/repositories/taskDetails.js, lib/notificationChannels/prComment.js, lib/notificationChannels/slack.js, lib/taskUpdate.js, views/artifacts/viewImageGalleryDiff.pug
This PR adds a viewer for the imagediff artifact type. This JSON type shows changed images, new and removed images when comparing two different image gallery types.
closes #611
=> ✨Added viewer for imagediff artifact type

bin/stampede-server.js, lib/queueHeartbeatHandler.js, services/notification.js
This PR adds a queue heartbeat notification that will send out the queue counts every 30 seconds.
closes #629
=> ✨ Added a queue heartbeat notification

views/admin/info.pug
This PR updates the info page with some additional details.
closes #664
=> 📝 Updated info page with more info

controllers/admin/serverSettings.js, views/admin/serverSettings.pug, views/components/sideBar.pug
This PR adds a new admin page that displays all the server settings that are currently defined.
closes #665
=> :✨ Added a server settings page for admins

controllers/admin/executeTaskConfig.js, controllers/admin/notifications/uploadChannel.js, controllers/admin/uploadDefaults.js, controllers/admin/uploadOverrides.js, controllers/admin/uploadQueues.js, controllers/admin/uploadRepositoryBuild.js, controllers/admin/uploadRepositoryConfig.js, controllers/admin/uploadTask.js, lib/task.js
This PR fixes several places where any yaml file errors wouldn't be handled correctly.
closes #261
=> 🐛 fixed some yaml file error handling

lib/taskUpdate.js
=> 🐛 fixed bug in how summary table was rendering in gh check

lib/taskUpdate.js
This PR removed the newline that was breaking the table markdown.
closes #690
=> 🐛 Removed newline that was breaking the table markdown

lib/checkRun.js
This PR adds the user login to the pull request details. This can be used by the worker to provide the value to work scripts.
In the task details this shows up in the JSON:
```
"pullRequest": {
"number": 61,
"head": {
"ref": "house/lint-warnings",
"sha": "2da6e30b04364a74e051bc31124be771c630a415"
},
"base": {
"ref": "master",
"sha": "83979a5c9052356d691f8df27c2c7c85698b259b"
},
"login": "davidahouse"
}
```
=> ✨Added login to pr details

lib/notificationChannels/httpPost.js, lib/notificationChannels/slack.js, package-lock.json, package.json, scm/github.js
This PR changes out the lynn-request dependency for axios. The latter is more well maintained and has more functionality.
=> ♻️ Changed out lynn-request dependency for axios
