events/pullRequest.js

This PR adds the action that we get when a PR based on a forked repo is updated. This action should trigger the checks just like a normal push/update.

🐛 added synchronize actions to trigger pr checks

---

lib/build.js
lib/task.js
lib/taskExecute.js

This PR adds the ability for the taskExecute request from the Portal to include a taskQueue that will override whatever the task is normally configured for. This allows you to manually execute tasks on any queue. Very helpful for testing a node as you can put the worker into a mode where it reads from a specific queue and then send a task to it directly.

✨ taskExecute now allows for overriding the task queue

---

events/checkSuite.js

This PR fixes a bug that was causing too many builds to run. Ignoring the check_suite `requested` action should fix this. So far I haven't seen a case where we need to respond to this for PRs since we also get the PR events.

🐛 Ignore the check_suite requested event

---

events/checkRun.js
events/checkSuite.js
events/pullRequest.js
events/push.js
events/release.js
scm/testMode.js

This PR updates the server to track repos that it receives events for, even if they have no .stampede.yaml file. This will allow for executing tasks, or setting up a cached config before the repo is updated.

✨ Now capturing repos that dont have a stampede file

---

views/repositories/repositoryDetails.pug

This PR removes the change build number button from the repository details screen as it is non-functional.
closes #219

🔥 Removed change build number button

---

events/checkRun.js
events/pullRequest.js
events/push.js
events/release.js
lib/build.js
lib/checkRun.js
lib/taskExecute.js
scm/github.js
scm/testMode.js

This PR adds new functionality to a PR where you can attach ad-hoc actions to the PR check. This allows you to configure tasks that only need to be run occasionally and can be triggered manually right from the GitHub UI. These actions show up in the Stampede check for a PR. They are configured the same as tasks (they are tasks!), but in a new key in the .stampede.yaml file named 'actions'.
For example:
```
pullrequests:
config:
tasks:
- id: lint-nodejs
actions:
- id: pr-standards
- id: test-config
- id: long-running
```
closes #170

✨ Actions can now be requested from a PR using the stampede check

---

api/executeTask.js
lib/api.js

This PR adds an API endpoint `/api/executeTask` for executing a single task in a repo. This doesn't require a .stampede.yaml as you are required to specify all the details for running the task. Note that the task must exist in the configuration of the system, however.
closes #175

✨Added API for executing a single task

---

lib/repositoryBuild.js

This PR fixes an issue with repository builds and how they were passing the branch name to the worker. This was causing errors in the worker with the STAMP_BRANCH environment variable not getting set properly.
closes #239

🐛 Fixed issue with repository build branch setting

---

lib/build.js
scm/github.js
scm/testMode.js

This PR adds an access token to the scm details that are sent to tasks. This allows tasks to access the GitHub API without having to authenticate themselves. This gives tasks the same permissions that the GitHub App has.

✨ Server now creates a temporary access token for tasks to use during build

---

scm/github.js

This PR adds some logging in the failed check update case so we can more closely diagnose the GitHub summary & text size limits.
closes #246

📢 Added logging for failed check update

---

lib/taskDetail.js

This PR fixes a bug causing task failures if the system overrides list was null.
closes #255

🐛 Fixed bug when system overrides was null

---

scm/github.js

This PR logs any errors received when creating check runs.

🐛 expose error when creating check runs

---

controllers/repositories/executeTask.js
controllers/repositories/executeTaskConfig.js
events/pullRequest.js
lib/checkRun.js

This PR removes some additional PR details that were added to the task info. These aren't provided by all the GitHub events, so it would be better to make the tasks fetch them if they are needed rather than making the server do it.
closes #269

♻️ Removed additional PR details from task scm info

---

bin/stampede-server.js

This PR fixes a bug in the server where the scheduler would error out if a build didn't have a schedule, such as a manual build.
closes #273

🐛 Fixed logic bug in scheduler

---

events/release.js

This PR fixes an issue caused by params in the release title.
closes #280

🐛 Sanitized params in release name

---

events/release.js

This PR adds the GitHub Release body text to the details sent to tasks. This can be used to take release notes entered into GitHub and display them on deployed apps. Or to append additional info back into the release text.
closes #282

✨ Now sending GitHub release body text to the task

---

controllers/repositories/executeRepositoryBuild.js
views/repositories/executeRepositoryBuild.pug

This PR adds a confirmation screen to the repository build execution. This gives details and a link to the Repository Details page to make it clear that users should go back to that page to see their build under Active Build. This is instead of a popup message per #279 but it should solve the root problem of starting a build but not knowing you did.
closes #279

♻️Added execute build confirmation screen

---

lib/build.js
scm/testMode.js

This PR removes the attempt to create a stampede check when the build starts. For non-PR builds this will fail anyway since we don't have checks on non-PRs in GitHub. Now the check is never attempted, saving an error message from the logs.
closes #283

🐛 Remove attempt to create stampede check if we are not in a pr build

---

bin/stampede-server.js

This PR fixes an issue where the server was sending notifications to an empty queue name. This was leaving unprocessed messages in redis.
closes #288

🐛 Fixed issue with empty notification queue list

---

api/history/tasks.js

This PR adds a new API endpoint `/api/history/tasks` which will return a list of the recent tasks. It accepts filters for time range, repository, status and node.
closes #290

✨Added task history to api

---

lib/checkRun.js
lib/task.js

This PR adjusts how PR actions are treated. Instead of creating a new build, now they are appending to the existing build with a unique task ID. Before the task ID would be the same for every execution. This can cause issues on the worker since it tries to clone to the same working folder. Also the Task ID can now be depended on to be unique if needed for publishing artifacts or other needs.
closes #300

🐛 PR task actions now are uniquely identified

---

scm/github.js

This PR changes the title of the Stampede check. Eventually it should probably be configurable, but for now it will be titled `Stampede Information`.

📝 Changed title of Stampede check

---

controllers/repositories/repositoryDetails.js
views/repositories/repositoryDetails.pug

This PR updates the stampede build list to show a message for any scheduled builds. These aren't meant to be executed manually, so instead we show a message letting the user know when the build is scheduled for. If the build is currently running it will show like other active builds.
closes #309

✨ Scheduled repository builds now show the fact

---

controllers/history/buildTaskDetails.js
controllers/history/taskDetails.js
controllers/monitor/buildTaskDetails.js
controllers/repositories/taskDetails.js
views/history/buildTaskDetails.pug
views/history/taskDetails.pug
views/monitor/buildTaskDetails.pug
views/repositories/taskDetails.pug

This PR hides the task config section for non-admins. This cleans up the task details a bit since most users don't need to see all the task config items. Once we add some fields to the task config to indicate which fields are secure, we can relax this restriction so that non-admins will see the config for non-secure items.
closes #317

✨ Hiding task config for non admins

---

controllers/admin/addRepository.js
controllers/admin/enterNewRepository.js
views/admin/enterNewRepository.pug
views/admin/repositories.pug

This PR adds the ability for admins to add repositories to the database.  This can be useful for cases where the repository hasn't had activity so it doesn't show up in the list yet. Then at least Admins can setup defaults & builds without requiring commits/etc to the repository.
closes #278

✨ Admins can now add repositories

---

lib/build.js
lib/db.js
scm/github.js

This PR handles the situation where a repository build starts but the Stampede GH app doesn't have rights for the repository. This can happen if the app was removed from the repo. Now the build will immediately fail if it can't get an access token for the repo.
closes #299

👷‍♂️ Better error handling for no access when starting repo build

---

controllers/monitor/cancelBuild.js
views/monitor/buildDetails.pug
views/monitor/cancelBuild.pug

This PR adds a cancel build button to the active build details screen. Note that this doesn't technically cancel the tasks, they will still run and perhaps complete the build. The cancel build just removes it from the active builds list.
closes #234

✨ Added a cancel build button to active build details

---

scm/github.js

This PR changes the behavior of a failed check run update. Now it will mark the check run as a failure. This is a stampede failure, but we shouldn't give the user the false impression that the task was fully successful. These failures will eventually be tagged as a system failure, but until then we want to see these as failures so the underlying problem can be addressed (and known that it happened).
closes #243

🐛 Mark a task as a failure if the check run details can't be applied

---

controllers/history/buildTimeByOrg.js
lib/db.js
package-lock.json
package.json
views/components/sideBar.pug
views/history/buildTimeByOrg.pug

This PR adds a new screen that shows task time per org based on a time filter. Note this is time per task, not the build as a whole. So it represents the amount of time spent running on a node.
closes #217

✨ Added a build time per org report

---

controllers/history/buildTimeByNode.js
lib/db.js
views/components/sideBar.pug
views/history/buildTimeByNode.pug

This PR adds a screen to view build time per node. This screen can be used to view how well tasks are distributed across nodes.
closes #216

✨ Build time per node report

---

controllers/repositories/repositoryDetails.js

This PR changes the time filter for Recent Builds on the Repository details screen to the last 7 days instead of just last 8 hours. Will still want a way to go directly to history to see even further back.
closes #361

♻️ Changed time filter for recent builds

---

controllers/repositories/repositoryDetails.js

This PR changes the Repository Details screen to add all active builds to the top section.
closes #347

✨ Now showing all active builds on repo details

---

events/push.js

This PR fixes an error that was caused by a GitHub event that didn't have a commit message.
closes #367

🐛 fixed error when commit message not in github event

---

events/push.js

This PR changes the behavior of the push event and no longer ignores branch creation events. Originally this was due to pull requests, but even for PR branches it is ok for the system to check the .stampede.yaml file to see if anything should be done for the branch. Now it would be possible to run some tasks just at the branch level in addition to the pull requests. Mostly this fixes an issue where someone creates a new branch and adds/changes their .stampede.yaml to match the branch and then pushes. They expect tasks to run in this case.
closes #369

✨ Stop ignoring push events that create branches

---

views/history/buildTaskDetails.pug
views/history/taskDetails.pug
views/repositories/taskDetails.pug

This PR makes the re-queue button on task details depend on admin access. Usually this operation is when the admin is working on an issue with a node or task script. And it might be confusing for average users.
closes #379

♻️ Make requeue button depend on admin access

---

views/components/sideBar.pug
views/repositories/taskDetails.pug

This PR fixes an issue where sometimes the sidebar background would disappear and the menu items would float over the top of the task details. This happened mostly when there was a task with a specific type of response. I think its due to the width, but not completely sure the trigger.
closes #362

🐛 Fixed sidebar sometimes going to 0 width

---

controllers/history/taskHealth.js

This PR fixes a bug in the task health screen where the repository filter didn't work.
closes #383

🐛 Fixed bug on task health repo filtering

---

api/monitor/activeBuilds.js
api/monitor/activeTasks.js
api/monitor/queueSummary.js
api/monitor/workerStatus.js
api/repository/recentBuilds.js

This PR moves some of the API endpoints under sub-folders to better match overall organization of the code and matches where these can be found in controllers/views. A few API will stay at the root as they are universal and might be used in several places, not just tied to a single folder.

♻️ Changed some API endpoints to fall under a subfolder

---

lib/db.js

This PR fixes the number of hours in hourly summary from 25 back to 24.
closes #396

🐛 fixed number of hours returned in hourly summary

---

controllers/admin/reports.js
controllers/admin/systemConfig.js
views/admin/reports.pug
views/admin/systemConfig.pug
views/components/sideBar.pug

This PR refactors the sidebar menu, moving some items under admin and creating 2 new groupings under admin: system config and reports. This will save on vertical space in the sidebar menu, allowing for more system config and reports to be created without worry of making the sidebar too big.
Also one side-effect is that non-admin users will no longer have access to a few screens which should have been admin only anyway. None of the screens that normal users need are hidden, they are still available.
closes #377

♻️ Moved some screens under admin

---

controllers/admin/addRepository.js

This PR fixes a bug that allowed for creating a repository with an empty owner or repository name (or both).
closes #401

🐛 prevent empty owner or repo to be added

---

lib/db.js

This PR changes when the tables are created. Now the server will attempt to create them when the first database connection is successful. As the db might not be immediately available when the server starts, this lets the server still start and then once the db is available it should create the tables and then function correctly.
closes #406

♻️ Creating tables now on first connection

---

controllers/history/requeueTask.js
controllers/repositories/requeueTask.js
scm/github.js

This PR addresses a bug in the access token creation for re-queued tasks. Also adds some verbose logging to show any access token creation errors.
closes #411 and closes #407

🐛 Addressed bug in access token

---

scm/github.js

This PR looks for very large text before trying to update the PR check. If the value is above the GitHub limit, an error message is specified instead.
closes #422

🐛 Prevent large amounts of text to error when updating PR check

---

controllers/repositories/repositoryBuildDetails.js
controllers/repositories/repositoryDetails.js
lib/db.js
views/components/tableUnderlinedCell.pug
views/repositories/repositoryBuildDetails.pug
views/repositories/repositoryDetails.pug

This PR reworks the repository build list on the repository details screen. Now the list will show an entry for each build that has been defined, and provides a link to a details page. The start button has moved to the details page. Also on the details page are the recents for that particular build. Now it is easier to find the results of a particular repository build. This may confuse users at first, but hopefully this works better in the long run since it allows for easily finding the recents for each of these manual/scheduled builds.
closes #418

♻️ reworked repository builds flow from repository details

---

.ubolt.yaml
bin/stampede-server.js
lib/web.js

This PR adds a config option to disable the response queue handler. This is part of the series of enable config options for disabling certain parts of the server when you want to spread the work across different instances of the server.
closes #434

✨ Added config option for response handler

---

bin/stampede-server.js
events/checkRun.js
events/checkSuite.js
events/pullRequest.js
events/push.js
events/release.js
incoming/github.js
lib/incomingHandler.js

This PR adds an incoming queue where GitHub events are placed and then handled separately. This should keep the reception of events fast so GitHub doesn't timeout and we lose a message. A config option is also available for disabling the incoming handling if you have instances of the server that shouldn't perform that work.
closes #425

✨ Added incoming queue for handling github events

---

bin/stampede-server.js
lib/buildScheduleHandler.js
lib/db.js
lib/retentionHandler.js

This PR updates the server to include a retention policy. Now older builds will be automatically deleted from the system. You can control this behavior using the `defaultBuildRetentionDays` and `defaultReleaseBuildRetentionDays` config values. Release builds are given a separate parameter as generally you want to keep these around much longer. Also you can execute a system task for any artifacts that were captured by the build using the `cleanupArtifactTask` config. This should contain the task ID for the task that you want to run on a worker. The server will queue up a single task execution for each artifact in the build. Also note these cleanup tasks will show up on the worker under the owner/repo of `system/system`. They will not show up in the list of running tasks in the system nor …

✨Retention policy handler

---

lib/db.js

This PR fixes a bug in the release ordering on the repository details screen.
closes #446

🐛 Fixed release ordering for repository details

---

controllers/history/buildTaskDetails.js
controllers/history/taskDetails.js
controllers/repositories/taskDetails.js
lib/db.js
lib/retentionHandler.js
views/history/buildTaskDetails.pug
views/history/taskDetails.pug
views/repositories/taskDetails.pug

This PR changes the retention handler to mark a build as archived instead of deleting it. We want to keep the builds around for reporting purposes, but we do want to cleanup the details. So this change also deletes the TaskDetails for any tasks in the archived build. It keeps the execution of the cleanup artifact task, although this might change in a subsequent PR. The last changes are to the task details screens to allow them to display a task without a task details record in the database.
closes #449

♻️ Changed retention to use archiving instead of deleting

---

bin/stampede-server.js
lib/retentionHandler.js

This PR removes the janky task execution for cleaning up an artifact. Now we just mark the build as archived in the retention handler and leave the task details in place. This allows admins to create their own mechanism for cleanup that is appropriate to their environment. We will add an API for fetching archive builds for further cleanup in a separate PR.
closes #455

🔥 Removed artifact cleanup task execution

---

api/history/archivedBuildWithTaskDetails.js
lib/db.js

This PR adds an API endpoint so that clients can fetch an archived build that has task details. These types of builds may require additional cleanup, for example when artifacts need to be cleaned up from an external system.
closes #456

✨Added API for fetching an archived build with task details

---

api/history/removeTaskDetails.js
lib/api.js

This PR adds an API for removing all task details for a build. Because task details take up some space in the database, removing them can save space. Also the presence of task details represents a build that might need archiving.
closes #457

✨ Added API for removing all task details for a build

---

controllers/repositories/repositoryDetails.js
views/repositories/repositoryDetails.pug

This PR removes the duplicates that can show up under Releases on the Repository Details screen.
closes #463

✨ Remove release duplicates on the repository details screen

---

controllers/repositories/repositorySourceDetails.js
lib/db.js

This PR changes the date range for the repository source details screen. Instead of only showing the last 30 days, we should show a much longer range of detail.
closes #464

♻️ Changed date range for repository source details screen

---

controllers/repositories/repositoryBuildDetails.js

This PR increases the date range on the repository build details screen. Now it will show the last most recent builds, making it easier to find when the last ones were executed.
closes #468

♻️ Increased date range on repository build details screen

---

lib/db.js

This PR changes the repository details screen to limit the builds shown to ones that aren't archived. This keeps the list focused on the recent builds only.
closes #471

♻️ Repository builds now showing non-archived builds

---

scm/github.js

This PR sets the details url for GitHub checks with a link to the task details for the checks task. Without the details url, GitHub will just take the user to the GitHub app root URL.
closes #415

🐛 Fixed details url in github check

---

controllers/history/taskSummary.js
views/history/taskSummary.pug

This PR updates the Task Summary report by breaking out the task stats by status. Now the success & failed executions are counted & summarized separately, along with the totals.
closes #484

💄 Show task summary stats by status

---

lib/task.js
lib/taskDetail.js

This PR updates task validation to check for required parameters when a task starts. Required parameters can be defined at the task level by adding `required: true` to the task param. Required parameters must have a value or else the task will fail immediately without being sent to a worker. Values can come from any source such as defaults or overrides, or in the task request itself.
closes #108

✨ Server now supports required task parameters

---

api/admin/configDefaults.js
api/admin/configOverrides.js
api/admin/queues.js
api/admin/tasks.js
api/buildDetails.js
api/history/tasks.js
api/monitor/activeBuilds.js
api/monitor/activeTasks.js
api/monitor/queueSummary.js
api/monitor/workerStatus.js
api/repositories.js
api/repository/recentBuilds.js
api/repository/repositoryBuilds.js
bin/stampede-server.js
lib/api.js
lib/ui.js
package-lock.json
package.json
views/components/sideBar.pug

This PR enables the server to be configured with a live API explorer that you can access from the Web UI. The explorer can be accessed via the `/api/api-docs` route, and also from the `API Docs` menu item. This explorer is disabled by default and can be enabled with the `enableApiDocs` server configuration parameter.
closes #482

✨Embedded API Explorer

---

api/repository/repositoryBuilds.js

This PR fixes the `lastExecuted` field in the repository builds API response. Instead of empty string it removes the element. 
closes #501

🐛 Remove lastExecuted if not available

---

api/repository/activeBuilds.js

This PR changes the recentBuilds API to an activeBuilds API. This matches more correctly the UI needs for repository details.
closes #503

♻️ Changed recentBuilds to activeBuilds API

---

controllers/history/buildSummary.js
controllers/history/builds.js
controllers/repositories/repositoryBuildDetails.js
controllers/repositories/repositorySourceDetails.js
lib/db.js
views/history/builds.pug

This PR adds Source as an additional filter on the History | Builds screen. This allows you to more quickly find particular builds such as a `release` or `branch` build.
closes #465

✨ Added source to build history filter

---

api/repository/buildKeys.js
controllers/repositories/repositoryDetails.js

This PR adds a new API endpoint to retrieve the build keys for a given repository and source combination. The mobile app can use this to show builds on the repository details screen.
closes #494

✨ New buildKey API

---

lib/cache/cache.js

This PR fixes a bug that was causing a crash if the system defaults or system overrides didn't have anything set in them.
closes #360

🐛 Fixed a bug if sys defaults or overrides not set

---

events/checkRun.js
events/checkSuite.js
events/pullRequest.js
events/push.js
events/release.js
lib/incomingHandler.js

This PR changes how a single check run is handled. Previously, when the user asked to re-run a single check, the entire set of checks would start because of reasons. Now only the single check run should re-run. This PR also changes all the event handlers for Github events, so might introduce other issues, but we will just need to do some testing.
closes #42

♻️ Changed how single check run rerequest is handled

---

controllers/history/builds.js
lib/db.js

This PR adds an additional filter to the build key on the build history screen. Now if you select a repository and filter on that, the build key will filter the list to show only build keys found in the repository selected.
closes #348

✨ Build key not filters by repository on build history

---

controllers/admin/reports/taskParameterValues.js
views/admin/reports.pug
views/admin/reports/taskParameterValues.pug

This PR adds a new admin report that will show all the values for parameters used in a task, across all executions/repositories for that task. So if you want to see how different repositories are using different values this report makes that easy to find. For example this can be used to see which projects are using which version of Xcode in a specific task.
Note that this only works for a single task at a time. Also for larger date ranges this is not a fast operation.
closes #529

✨ New report for viewing parameter values across a task

---

bin/stampede-server.js
controllers/history/buildDetails.js
controllers/history/buildTaskDetails.js
controllers/history/taskDetails.js
controllers/monitor/buildDetails.js
controllers/monitor/buildTaskDetails.js
controllers/repositories/buildDetails.js
controllers/repositories/taskDetails.js
lib/db.js
lib/taskArtifact.js
lib/taskUpdate.js

This PR modifies the server to include an artifacts table that stores all the task artifacts. Previously this data was a part of the taskDetails json object, but moving this to its own table has some benefits for accessing artifacts more quickly. This will open up functionality in the future for viewing artifacts in Stampede directly, along with doing diff comparisons between branches or between a PR and a default branch.
Note: This PR is backward compatible with worker instances and existing task details that contain artifacts in the JSON. There is no migration code here to move artifacts from taskDetails, although that might be something we could add in the future if needed.
closes #508

✨Artifacts table

---

events/checkRun.js

This PR fixes a bug when re-running a task from GitHub.
closes #532

🐛 Fixed bug when re-running a task

---

controllers/admin/notifications/channelConfig.js
controllers/admin/notifications/notificationChannels.js
controllers/admin/notifications/removeChannel.js
controllers/admin/notifications/uploadChannel.js
lib/cache/cache.js
lib/cache/notifications.js
views/admin/notifications/channelConfig.pug
views/admin/notifications/notificationChannels.pug
views/admin/systemConfig.pug

This PR adds notification channel admin to the system. You can add/remove channels under the System Config menu option. Similar to tasks, the required fields in the channel config yaml file are `id` and `title`.
With this PR in place, we can start to work on the notification routing & provider tasks. As we implement them, we might have some adjustments here as well.
closes #536

✨ Added notification channel config to admin screens

---

lib/cache/cache.js

This PR fixes a bug where the task config redis entry isn't deleted if the task is deleted. This doesn't cause any harm, but it does leave droppings in redis… 💩 
closes #538

🐛 fixed bug removing task config

---

controllers/admin/notifications/channelConfig.js

This PR fixes an error when viewing the notification channel details when the channel has no config parameters.
closes #545

🐛 Fixed error when viewing notification channel details

---

controllers/artifacts/viewCloc.js
controllers/history/buildDetails.js
controllers/history/buildTaskDetails.js
controllers/history/taskDetails.js
controllers/repositories/buildDetails.js
controllers/repositories/taskDetails.js
services/prCommentNotificationQueue.js
services/slackNotificationQueue.js
views/artifacts/viewCloc.pug
views/history/buildDetails.pug
views/history/buildTaskDetails.pug
views/history/taskDetails.pug
views/repositories/buildDetails.pug
views/repositories/taskDetails.pug

This PR adds a viewer in the UI for artifacts of type `cloc`. This is the first of many native viewers that will be created. This allows users to view data right in the Stampede UI and prevents the need to go into other systems, or download files. This viewer will show the output of the `cloc` command line app and show the number of lines of code per language.
closes #551

✨ Add viewer for CLOC json artifacts

---

lib/taskUpdate.js
scm/testMode.js

This PR adds artifact links in the GitHub check summary. Now developers can get access directly to any artifact downloads or links directly from the GitHub check, without having to view it in the Stampede UI.
closes #550

✨ Added artifact links to check summary

---

lib/notificationChannels/prComment.js
lib/taskUpdate.js

This PR fixes a bug where the cloc artifact urls were missing an ending ).
closes #561

🐛 fixed cloc artifact urls

---

lib/repositoryBuild.js

This PR fixes an issue that was causing repository builds to not generate notifications. Now any notifications configured for the repo builds will be executed.
closes #564

🐛 Allow notifications for repo builds

---

scm/events/release.js

This PR fixes an issue where the server would start a release build if there was no release title. This causes some issues in the UI and pathing since a release title is what is used to identify the build in the system. Now the server will prevent the build from starting.
closes #563

🐛 Prevent build from starting if release title is empty

---

controllers/repositories/buildDetails.js
lib/db.js

This PR fixes the list of tasks on any of the build details screen. This should order the tasks in the order they were started, putting any re-queued tasks at the end of the list.
closes #569

🐛 fixed ordering of tasks in a build details

---

lib/notificationChannels/prComment.js

This PR fixes a bug that was causing the task status emoji to be incorrect in the PR comment.
closes #578

🐛 Fixed task status in pr comment

---

api/history/builds.js

This PR adds an API endpoint for the build history, similar to task history.
closes #588

✨ Build history API

---

bin/stampede-server.js
lib/notificationChannels/prComment.js
lib/notificationChannels/slack.js

This PR allows the admin to customize the url used in the PR comment or Slack notification. This can be used to direct users to the mobile app instead of the web, for example.
closes #593

✨ More info URL for slack & pr comment now configurable

---

api/repository/buildDetails.js

This PR adds a new API endpoint that will retrieve a single build details. `/api/repositories/buildDetails`.
closes #595

✨ Added build details API

---

views/history/buildDetails.pug
views/history/buildTaskDetails.pug
views/history/taskDetails.pug
views/repositories/buildDetails.pug
views/repositories/taskDetails.pug

This PR adjusts the Info button for metadata so that it is only visible for admins. These metadata items are meant to be underlying system details, not user meaningful.
closes #597

♻️ Made metadata viewer admin only

---

api/repository/taskDetails.js

This PR ensures that SCM details contains strings for values. This was mostly an issue with the PR number field.
closes #603

🐛 Ensure scm details is returning strings

---

api/repository/taskArtifactContents.js

This PR adds a new API endpoint for getting the task artifact contents directly.
closes #602

✨ New api for getting task artifact contents directly

---

api/repository/repositorySourceBuilds.js

This PR adds a new API for retrieving the builds given a repo and build_key. This matches the drill down in the UI when you click on a branch/release/pull request from the repository details screen.
closes #608

✨ new api for repository source builds

---

lib/notificationChannels/prComment.js

This PR fixes an error that was happening on the server when a PR comment had failing tasks in it.
closes #614

🐛 Fixed error when there are failing tasks in a pr comment

---

lib/notificationChannels/prComment.js
lib/notificationChannels/slack.js
services/notification.js

This PR fixes an issue where the filter for notifications wasn't working. Now `all`, `started`, `completed`, `completedSuccess` and `completedFailure` are working.
closes #616

🐛Fixed bug in filtering notifications

---

api/monitor/queueSummary.js
controllers/monitor/queues.js
views/monitor/queues.pug

This PR separates the display for task queues and system queues. Now the system queues will be displayed automatically so the admins don't have to define them in the queues.yaml file.
closes #624

♻️ Separate task and system queues in display and api

---

bin/stampede-server.js
lib/notificationChannels/httpPost.js
services/notification.js
services/notificationChannelQueue.js

This PR adds a http post notification channel for queue summary updates that can be enabled via config option: queueSummaryNotificationURL. Should be able to add more notifications to this channel in the future very easily.
closes #625

✨ Enabled a http post notification channel for queue summary updates

---

api/monitor/queueSummary.js
controllers/monitor/queues.js
lib/queueHeartbeatHandler.js

This PR fixes a bug that was causing the queue heartbeat to fail due to no connections available.
closes #636

🐛 Closing queues that are opened for getting stats

---

api/repository/taskDetails.js
controllers/history/buildDetails.js
controllers/history/buildTaskDetails.js
controllers/history/taskDetails.js
controllers/repositories/buildDetails.js
controllers/repositories/taskDetails.js
lib/notificationChannels/prComment.js
lib/notificationChannels/slack.js
lib/taskUpdate.js
views/history/buildDetails.pug
views/history/buildTaskDetails.pug
views/history/taskDetails.pug
views/monitor/buildDetails.pug
views/monitor/buildTaskDetails.pug
views/repositories/buildDetails.pug
views/repositories/taskDetails.pug

This PR modifies the server UI to show an `Install` button for any `installplist` artifact types. These artifacts can be used to install apps on iOS devices. This is mostly just a UI change since Stampede already supports artifacts of the `link` type. But adding the UI for `Install` makes it clear the link points to a plist file that can install the app on an iOS device.
closes #606

✨ Support installplist artifact types

---

api/repository/taskDetails.js
controllers/history/buildDetails.js
controllers/history/buildTaskDetails.js
controllers/history/taskDetails.js
controllers/repositories/buildDetails.js
controllers/repositories/taskDetails.js
lib/notificationChannels/prComment.js
lib/notificationChannels/slack.js
lib/taskUpdate.js

This PR wraps the install app plist correctly so you can share the link provided in the Stampede UI and it should launch and install correctly on an iOS device.
closes #643

♻️Wrap install app plist url

---

controllers/help/taskHelp.js
controllers/help/tasks.js
views/admin/taskConfig.pug
views/help/taskHelp.pug
views/help/tasks.pug

This PR adds a dynamic task list to the Help | Tasks screen. This is pulled from the task config that the admins have defined. Also included are new parameters available in the task config including a task description, parameter description, allowed list of values and if the parameter is an admin only parameter or not. Now the system admins can document the tasks and have that displayed for all users, including an example of how to add that task to your stampede file.
closes #510

✨ Added dynamic task help page

---

api/repository/taskDetails.js
controllers/history/buildTaskDetails.js
controllers/history/taskDetails.js
controllers/monitor/buildTaskDetails.js
controllers/repositories/taskDetails.js
lib/taskDetail.js

This PR brings back the display of task config params to the task details screen. Now users can see the params that are associated with a particular task execution. If there are task params marked `adminParam` then these will not be displayed unless you are logged in as an admin.
closes #653

✨ Now showing task params again, hiding adminParams if not admin

---

lib/task.js
lib/taskDetail.js

This PR adds validation to a task param values based on the `allowedValues` option inside the task definition. So if a task param is configured with some `allowedValues`, but then the task execution doesn't include a value from the list, the task immediately fails. This is similar to how required values work.
closes #652

✨ Added validation based on allowedValues config in task definition

---

bin/stampede-server.js
lib/cache/cache.js
views/monitor/workers.pug

This PR changes the worker heartbeat storage to allow for extending the time the worker heartbeat is kept in memory. This allows the worker status screen to display a status if the worker hasn't reported in 30 seconds. By default the missing worker will show in the portal for an hour, but then will drop off the list.
closes #621

♻️ Adjusted worker timeout mechanism to remember recent workers

---

lib/db.js

This PR changes the filter on the repository details queries to return archived builds under branches and releases. For infrequently used repos we want to at least show something under these, even if the builds are old and archived.
closes #670

♻️ Removed archive filter for branch and release builds on repo details

---

bin/stampede-server.js
lib/cache/cache.js
lib/cache/cacheClient.js
scm/events/pullRequest.js
scm/events/push.js
scm/events/release.js

This PR updates the server to store incoming GitHub events in the Redis cache. By default the system will store the last 10 events that are either for a pull request, branch push or release. The check suite/run events are not being stored right now since those are more internal to GitHub <-> Stampede communication. By storing these main events that are hard to recreate, we can build a UI inside Stampede where the Admins can see these events and re-trigger them. This is better than the GitHub UI for doing this since it doesn't break things up by repo. This is the first of several PRs to fully implement the functionality. This PR simply stores the incoming events.
Use the `repoEventLimit` server configuration parameter to adjust the number of events. If you set this value to 0, no events …

✨ Server now stores incoming github events for main source events

---

controllers/admin/viewRepoEventDetails.js
controllers/admin/viewRepoEvents.js
lib/cache/cache.js
scm/events/pullRequest.js
scm/events/push.js
scm/events/release.js
views/admin/repositoryAdmin.pug
views/admin/viewRepoEventDetails.pug
views/admin/viewRepoEvents.pug

This PR adds a screen to the Admin section under the Repository details screen which allows for viewing the SCM events for that repo. This will show the latest events that have been received. The number of events by default is 10, but you can configure this with a server parameter.
closes #382

✨ Added a screen for viewing repo events

---

controllers/admin/executeRepoEvent.js
controllers/admin/viewRepoEventDetails.js
scm/events/pullRequest.js
scm/events/push.js
scm/events/release.js
services/incomingQueue.js
views/admin/executeRepoEvent.pug
views/admin/viewRepoEventDetails.pug

This PR adds an Execute button to the scm event details screen. This can be used to re-execute an event for a particular repository. Note that this will create a new event in the history since it will be captured again by the system as it appears just like a normal event.
closes #677

✨ Added execute button for scm events

---

api/repository/taskDetails.js
controllers/history/taskDetails.js
controllers/monitor/buildTaskDetails.js
controllers/repositories/taskDetails.js
lib/taskUpdate.js
views/components/resultSummary.pug
views/history/buildTaskDetails.pug
views/history/taskDetails.pug
views/monitor/buildTaskDetails.pug
views/repositories/taskDetails.pug

This PR adds support for rendering the new `summaryTable` task result. This is supported in the latest stampede-worker version and allows for displaying tabular data in the summary without having to create the markdown directly. Adding native table support makes this look better in the UI and also will improve how it looks in the mobile app. Support for `shields.io` badges inside the table also further improve how the summary looks.
Using the summaryTable can be an alternate to the markdown summary, or can be used together with it. See the stampede-worker release for details on how to format the stampede table json so it will be rendered correctly.
closes #682

✨Support for rendering Summary Table in UI and GitHub check

---

bin/stampede-server.js
lib/notificationChannels/prComment.js
lib/notificationChannels/slack.js
lib/taskUpdate.js

This PR adds a new config option: `autoRenderArtifactListComment` which disables the automatic rendering of the artifact list links in GitHub check summaries, PR comments and Slack notifications. The default is still enabled so existing installations will continue to work as configured. But for cases where are more streamlined summary is desired, this can be disabled and then you can optionally include the links to the artifacts desired in the summary or summaryTable itself.
closes #684

✨ New config option to disable artifact list auto rendering

---

lib/notificationChannels/prComment.js
lib/notificationChannels/slack.js
scm/testMode.js

This PR adds the streamlined summary table as a style option for the PR Comment. To enable this, just add `style: summaryTable` to the channel config for the PR comment notification channel. When enabled, the output will be a table format instead of the possibly more verbose summary text.
This PR also adjusts the Slack output slightly to make it more streamlined. Slack doesn't support using badge images very well, so instead of supporting the summary table it only supports this new more streamlined mode.
closes #683

✨ Now supporting streamlined summary table in pr comment

---

lib/taskUpdate.js

This PR fixes a minor rendering glitch in the GitHub checks if a task doesn't have any summary table information. Previously it would render the table header but because there are no rows, GitHub would display two small boxes for that table. This PR removes the table completely in these cases.
closes #692

🐛 Only render markdown table if summary table has rows

---

bin/stampede-server.js
controllers/admin/viewRepoParseErrors.js
lib/cache/cache.js
lib/cache/cacheClient.js
lib/config.js
scm/github.js
scm/testMode.js
views/admin/repositoryAdmin.pug
views/admin/viewRepoParseErrors.pug

This PR adds capturing for YAML parse errors when the system is trying to parse a repositories stampede.yaml file. Before there was little indication of any problem, only that nothing worked. While there was some logging in the server, it was hard to isolate. So now the server stores these errors for a limited amount of time. You can find them in the Admin Repository details screen.
closes #566

✨ Now capturing yaml parse errors in stampede config files

---

Dockerfile
bin/stampede-server.js
controllers/admin/performLogin.js
package-lock.json
package.json
scm/events/pullRequest.js
services/incomingQueue.js

This PR updates the Dockerfile to node 18 and brings most of the other NPM dependencies up to the latest versions. This should eliminate most of the current audit warnings.

⬆️ Updated dependencies and moved to node version 18
